# Generated by Django 4.0.1 on 2024-04-06 09:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manhdat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieuKhien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lamp_time_on', models.TimeField(default=datetime.time(18, 0))),
                ('lamp_time_off', models.TimeField(default=datetime.time(6, 0))),
                ('water_pump_on', models.IntegerField(default=50)),
                ('water_pump_off', models.IntegerField(default=70)),
                ('fan_on', models.IntegerField(default=35)),
                ('fan_off', models.IntegerField(default=25)),
                ('sun_roof_time_close', models.TimeField(default=datetime.time(11, 0))),
                ('sun_roof_time_open', models.TimeField(default=datetime.time(14, 0))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manhdat', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manhdat.manhdat')),
            ],
        ),
    ]
